name = "my-chat-app"
main = "app.py"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # الاسم البرمجي الذي سنستخدمه
database_name = "live-chat"
database_id = "ea6fda78-ba8c-49e0-be6c-aa15e3961dc1"